#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { compileModule } from "./frontend/index";

function showUsage(): never {
  console.error("Usage: jue-compile --input <file> --output <file> [--root-symbol <symbol>]");
  process.exit(1);
}

function main() {
  const args = process.argv.slice(2);
  const inputIndex = args.indexOf("--input");
  const outputIndex = args.indexOf("--output");
  const rootSymbolIndex = args.indexOf("--root-symbol");

  if (inputIndex === -1 || outputIndex === -1) {
    showUsage();
  }

  const inputPath = args[inputIndex + 1];
  const outputPath = args[outputIndex + 1];
  const rootSymbol = rootSymbolIndex !== -1 ? args[rootSymbolIndex + 1] : undefined;

  if (!inputPath || !outputPath) {
    showUsage();
  }

  const source = readFileSync(inputPath, "utf8");
  const result = compileModule(source, rootSymbol ? { rootSymbol } : undefined);

  if (!result.ok) {
    console.error(`Compile error: ${result.error.code}: ${result.error.message}`);
    process.exit(1);
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(
    outputPath,
    `/* @generated by jue-compile */\n${result.value.code}\n`
  );
}

main();
