/* @generated by scripts/compile-example-components.ts */

    import { createBlueprint } from "@jue/runtime-core";

    let pressCount = 0;
function handleClick() {
  pressCount += 1;
  console.log("Button clicked!");
}
function handleClickPressCount() {
  return pressCount;
}

    const blueprintResult = createBlueprint({
      nodeCount: 8,
      nodeKind: new Uint8Array([1,1,2,1,2,2,1,2]),
      nodePrimitiveRefIndex: new Uint32Array([0,1,4294967295,3,4294967295,4294967295,6,4294967295]),
      nodeTextRefIndex: new Uint32Array([4294967295,4294967295,2,4294967295,4,5,4294967295,7]),
      nodeParentIndex: new Uint32Array([4294967295,0,1,0,3,3,0,6]),
      bindingOpcode: new Uint8Array([0,5]),
      bindingNodeIndex: new Uint32Array([5,6]),
      bindingDataIndex: new Uint32Array([0,0]),
      bindingArgU32: new Uint32Array([8,9]),
      bindingArgRef: ["View", "Text", "1Compiled from a", "Text", "Signal value:", "", "Button", "Click 11me", "onPress", handleClick],
      regionType: new Uint8Array([]),
      regionAnchorStart: new Uint32Array([]),
      regionAnchorEnd: new Uint32Array([]),
      regionBranchRangeStart: new Uint32Array([]),
      regionBranchRangeCount: new Uint32Array([]),
      regionBranchNodeStart: new Uint32Array([]),
      regionBranchNodeEnd: new Uint32Array([]),
      regionNestedBlockSlot: new Uint32Array([]),
      regionNestedBlueprintSlot: new Uint32Array([]),
      regionNestedMountMode: new Uint8Array([]),
      signalToBindingStart: new Uint32Array([0]),
      signalToBindingCount: new Uint32Array([1]),
      signalToBindings: new Uint32Array([0])
    });

    if (!blueprintResult.ok) {
      throw new Error(blueprintResult.error.message);
    }

    export const blueprint = blueprintResult.value;
    export const signalCount = 1;
    export const initialSignalValues = ["xxx1"];
    export const handlers = { "handleClick": handleClick, "handleClickPressCount": handleClickPressCount };
  
