/* @generated by scripts/compile-example-components.ts */

    import { createBlueprint } from "@jue/runtime-core";

    let primaryActionCount = 0;
let syncActionCount = 0;
let escalateActionCount = 0;
function handlePrimaryAction() {
  primaryActionCount += 1;
  console.log("Primary action executed");
}
function handleSyncAction() {
  syncActionCount += 1;
  console.log("Sync action executed");
}
function handleEscalateAction() {
  escalateActionCount += 1;
  console.log("Escalate action executed");
}
function getPrimaryActionCount() {
  return primaryActionCount;
}
function getSyncActionCount() {
  return syncActionCount;
}
function getEscalateActionCount() {
  return escalateActionCount;
}

    const blueprintResult = createBlueprint({
      nodeCount: 70,
      nodeKind: new Uint8Array([1,1,1,1,2,1,2,1,2,1,1,2,1,2,1,2,1,2,1,1,1,2,1,2,1,1,2,1,2,1,1,2,1,2,1,1,1,2,1,2,1,1,2,1,2,1,1,2,1,2,1,1,1,2,1,2,1,1,2,1,2,1,2,1,2,1,1,2,1,2]),
      nodePrimitiveRefIndex: new Uint32Array([0,1,2,3,4294967295,5,4294967295,7,4294967295,9,10,4294967295,12,4294967295,14,4294967295,16,4294967295,18,19,20,4294967295,22,4294967295,24,25,4294967295,27,4294967295,29,30,4294967295,32,4294967295,34,35,36,4294967295,38,4294967295,40,41,4294967295,43,4294967295,45,46,4294967295,48,4294967295,50,51,52,4294967295,54,4294967295,56,57,4294967295,59,4294967295,61,4294967295,63,4294967295,65,66,4294967295,68,4294967295]),
      nodeTextRefIndex: new Uint32Array([4294967295,4294967295,4294967295,4294967295,4,4294967295,6,4294967295,8,4294967295,4294967295,11,4294967295,13,4294967295,15,4294967295,17,4294967295,4294967295,4294967295,21,4294967295,23,4294967295,4294967295,26,4294967295,28,4294967295,4294967295,31,4294967295,33,4294967295,4294967295,4294967295,37,4294967295,39,4294967295,4294967295,42,4294967295,44,4294967295,4294967295,47,4294967295,49,4294967295,4294967295,4294967295,53,4294967295,55,4294967295,4294967295,58,4294967295,60,4294967295,62,4294967295,64,4294967295,4294967295,67,4294967295,69]),
      nodeParentIndex: new Uint32Array([4294967295,0,1,2,3,2,5,2,7,2,9,10,9,12,9,14,9,16,1,18,19,20,19,22,18,24,25,24,27,18,29,30,29,32,1,34,35,36,35,38,34,40,41,40,43,34,45,46,45,48,1,50,51,52,51,54,50,56,57,56,59,56,61,56,63,1,65,66,65,68]),
      bindingOpcode: new Uint8Array([2,2,2,2,0,2,0,2,0,2,2,0,2,5,2,5,2,5,2,2,2,0,2,0,2,2,0,2,0,2,2,0,2,0,2,2,2,0,2,0,2,2,0,2,0,2,2,0,2,0,2,2,2,0,2,0,2,2,0,2,0,2,0,2,0,2,2,0,2,0]),
      bindingNodeIndex: new Uint32Array([0,1,2,3,4,5,6,7,8,9,10,11,12,12,14,14,16,16,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69]),
      bindingDataIndex: new Uint32Array([0,2,4,6,2,8,3,10,4,12,14,12,16,18,20,22,24,26,28,30,32,5,34,6,36,38,7,40,8,42,44,9,46,10,48,50,52,13,54,14,56,58,15,60,16,62,64,17,66,18,68,70,72,19,74,20,76,78,21,80,22,82,23,84,24,86,88,28,90,29]),
      bindingArgU32: new Uint32Array([0,70,1,71,30,72,31,73,32,74,33,75,34,76,11,77,25,78,79,80,26,81,82,83,27,84,85,86,35,87,36,88,37,89,38,90,39,91,40,92,41,93,42,94,43,95,44,96,45,97,46,98,47,99,48,100,49,101,50,102,51,103,52,104,53,105,54,106,55,107,56,108,57,109,58,110,59,111,60,112,61,113,62,114,63,115,64,116,65,117,66,118]),
      bindingArgRef: ["View", "ScrollView", "View", "Text", "", "Text", "", "Text", "", "View", "Text", "", "Button", "Arm response", "Button", "Sync convoy", "Button", "Escalate lane", "View", "View", "Text", "", "Text", "", "View", "Text", "", "Text", "", "View", "Text", "", "Text", "", "View", "View", "Text", "", "Text", "", "View", "Text", "", "Text", "", "View", "Text", "", "Text", "", "View", "View", "Text", "", "Text", "", "View", "Text", "", "Text", "", "Text", "", "Text", "", "View", "Text", "", "Text", "", "className", "className", "className", "className", "className", "className", "className", "className", "className", "onPress", handlePrimaryAction, "className", "onPress", handleSyncAction, "className", "onPress", handleEscalateAction, "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className", "className"],
      regionType: new Uint8Array([]),
      regionAnchorStart: new Uint32Array([]),
      regionAnchorEnd: new Uint32Array([]),
      regionBranchRangeStart: new Uint32Array([]),
      regionBranchRangeCount: new Uint32Array([]),
      regionBranchNodeStart: new Uint32Array([]),
      regionBranchNodeEnd: new Uint32Array([]),
      regionNestedBlockSlot: new Uint32Array([]),
      regionNestedBlueprintSlot: new Uint32Array([]),
      regionNestedMountMode: new Uint8Array([]),
      signalToBindingStart: new Uint32Array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66]),
      signalToBindingCount: new Uint32Array([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]),
      signalToBindings: new Uint32Array([0,1,4,6,8,21,23,26,28,31,33,10,11,37,39,42,44,47,49,53,55,58,60,62,64,12,14,16,67,69,2,3,5,7,9,18,19,20,22,24,25,27,29,30,32,34,35,36,38,40,41,43,45,46,48,50,51,52,54,56,57,59,61,63,65,66,68])
    });

    if (!blueprintResult.ok) {
      throw new Error(blueprintResult.error.message);
    }

    export const blueprint = blueprintResult.value;
    export const signalCount = 67;
    export const initialSignalValues = ["ops-deck","ops-shell","ORBITAL CONTROL","Fleet Readiness Deck","A compiled TSX operations page that renders through Blueprint tables, keeps host primitives explicit, and preserves module-scoped action handlers.","Active missions","128","Crew latency","14 ms","Dock capacity","72%","ops-badge ops-badge--steady","Nominal orbit","Recovery lane","Three damaged relays are queued for cold-swap. The current plan keeps the comms mesh stable while repair crews rotate.","Convoy sync","Two escort wings are staging for the outer-ring convoy. Navigation windows are locked, but fuel arbitration still needs final sign-off.","Signal hygiene","The Babel frontend is now generating executable modules at build time. Browser bundles no longer carry parser/traverse overhead.","Operator directives","This pane is intentionally dense: multiple cards, metrics, sections, and button handlers authored as TSX, emitted as TS/JS, then mounted through the runtime.","Next window","06:30 UTC  |  Relay swap starts","07:10 UTC  |  Convoy escort sync","08:00 UTC  |  Dock pressure rebalance","ops-button ops-button--primary","ops-button ops-button--secondary","ops-button ops-button--ghost","Compiled from .tsx to executable module output.","Signal slots, event refs, and host nodes stay explicit.","ops-hero","ops-kicker","ops-title","ops-copy","ops-hero-row","ops-metrics","ops-metric-card","ops-metric-label","ops-metric-value","ops-metric-card","ops-metric-label","ops-metric-value","ops-metric-card","ops-metric-label","ops-metric-value","ops-grid","ops-story-card","ops-story-title","ops-story-body","ops-story-card","ops-story-title","ops-story-body","ops-story-card","ops-story-title","ops-story-body","ops-panel","ops-panel-main","ops-panel-title","ops-panel-body","ops-timeline","ops-panel-title","ops-timeline-item","ops-timeline-item","ops-timeline-item","ops-footer","ops-footer-label","ops-footer-value"];
    export const handlers = { "handlePrimaryAction": handlePrimaryAction, "handleSyncAction": handleSyncAction, "handleEscalateAction": handleEscalateAction, "getPrimaryActionCount": getPrimaryActionCount, "getSyncActionCount": getSyncActionCount, "getEscalateActionCount": getEscalateActionCount };
  
