import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { tsImport } from "tsx/esm/api";
import type { compileModule as compileModuleFn } from "@jue/compiler/frontend";

import { listExampleApps } from "./examples.js";

type CompilerModule = {
  readonly compileModule: typeof compileModuleFn;
};

export async function compileExampleComponents() {
  const compilerPath = fileURLToPath(new URL("../../../kernel/compiler/src/frontend/index.ts", import.meta.url));
  const compilerUrl = pathToFileURL(compilerPath).href;
  const { compileModule } = await tsImport(compilerUrl, import.meta.url) as CompilerModule;
  const examples = await listExampleApps();

  for (const example of examples) {
    const source = await readFile(example.componentPath, "utf8");
    const compiled = compileModule(source);
    if (!compiled.ok) {
      throw new Error(`${example.componentPath}: ${compiled.error.code}: ${compiled.error.message}`);
    }

    const outputPath = example.generatedModulePath;
    await mkdir(dirname(outputPath), { recursive: true });

    await writeFile(
      outputPath,
      `/* @generated by @jue/lab compile-examples */\n${compiled.value.code}\n`,
      "utf8"
    );
  }
}
