import { createRequire } from "node:module";
import { readFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";

import { tsImport } from "tsx/esm/api";
import type { compileModule as compileModuleFn } from "../../../../packages/compiler/src/frontend/index";
import type { compileSkylineSource as compileSkylineSourceFn } from "../../../../packages/skyline/src/index";

type CompilerModule = {
  readonly compileModule: typeof compileModuleFn;
};

type SkylineModule = {
  readonly compileSkylineSource: typeof compileSkylineSourceFn;
};

const require = createRequire(import.meta.url);
const compilerPath = fileURLToPath(
  new URL("../../../../packages/compiler/src/frontend/index.ts", import.meta.url)
);
const skylinePath = fileURLToPath(
  new URL("../../../../packages/skyline/dist/index.cjs", import.meta.url)
);
const sourcePath = fileURLToPath(new URL("../src/app.component.tsx", import.meta.url));
const cssPath = fileURLToPath(new URL("../src/mobile.css", import.meta.url));

export async function buildBrowserGeneratedModule(): Promise<string> {
  const compiler = await tsImport(pathToFileURL(compilerPath).href, import.meta.url) as CompilerModule;
  const source = await readFile(sourcePath, "utf8");
  const compiled = compiler.compileModule(source, {
    rootSymbol: "App"
  });

  if (!compiled.ok) {
    throw new Error(`${compiled.error.code}: ${compiled.error.message}`);
  }

  return `/* @generated by examples/mobile/jue-mobile-showcase/scripts/compile-browser.ts */\n${compiled.value.code}\n`;
}

export async function buildMiniprogramOutputs(): Promise<Readonly<Record<string, string>>> {
  const skyline = require(skylinePath) as SkylineModule;
  const source = await readFile(sourcePath, "utf8");
  const wxss = sanitizeForMiniprogram(await readFile(cssPath, "utf8"));
  const compiled = skyline.compileSkylineSource(source, {
    rootSymbol: "App"
  });

  if (!compiled.ok) {
    throw new Error(`${compiled.error.code}: ${compiled.error.message}`);
  }

  const artifactJson = JSON.stringify(compiled.value, null, 2);
  const pageDataJson = JSON.stringify({ signals: compiled.value.signalData }, null, 2);
  const projectConfigJson = JSON.stringify(
    {
      appid: "touristappid",
      projectname: "jue-mobile-showcase",
      compileType: "miniprogram",
      miniprogramRoot: "miniprogram",
      srcMiniprogramRoot: "miniprogram",
      setting: {
        es6: true,
        minified: false,
        postcss: true,
        enhance: true
      }
    },
    null,
    2
  );
  const appJson = JSON.stringify(
    {
      pages: ["pages/showcase/index"],
      window: {
        navigationBarTitleText: "jue mobile showcase",
        navigationBarBackgroundColor: "#f5f3ea",
        navigationBarTextStyle: "black",
        backgroundColor: "#f5f3ea"
      }
    },
    null,
    2
  );
  const pageJson = JSON.stringify(
    {
      navigationBarTitleText: "jue mobile showcase"
    },
    null,
    2
  );
  const sitemapJson = JSON.stringify(
    {
      desc: "Generated by jue mobile showcase"
    },
    null,
    2
  );

  return {
    "project.config.json": `${projectConfigJson}\n`,
    "miniprogram/app.json": `${appJson}\n`,
    "miniprogram/app.js": `/* @generated by examples/mobile/jue-mobile-showcase/scripts/generate-miniprogram.ts */
App({});
`,
    "miniprogram/sitemap.json": `${sitemapJson}\n`,
    "miniprogram/generated/showcase.artifact.json": `${artifactJson}\n`,
    "miniprogram/pages/showcase/index.json": `${pageJson}\n`,
    "miniprogram/pages/showcase/index.js": `/* @generated by examples/mobile/jue-mobile-showcase/scripts/generate-miniprogram.ts */
const artifact = ${artifactJson};

Page({
  data: ${pageDataJson}
});
`,
    "miniprogram/pages/showcase/index.wxml": `<!-- @generated by examples/mobile/jue-mobile-showcase/scripts/generate-miniprogram.ts -->\n${compiled.value.templateCode}\n`,
    "miniprogram/pages/showcase/index.wxss": `/* @generated by examples/mobile/jue-mobile-showcase/scripts/generate-miniprogram.ts */\n${wxss}\n`
  };
}

function sanitizeForMiniprogram(source: string): string {
  let css = source;

  css = removeSelectorBlock(css, ":root");
  css = removeSelectorBlock(css, "*");
  css = removeSelectorBlock(css, "body");
  css = removeSelectorBlock(css, "#app");

  css = css.replace(
    "width: min(100%, 360px);",
    "width: 100%;\n  max-width: 360px;"
  );

  return css.trim();
}

function removeSelectorBlock(source: string, selector: string): string {
  const escapedSelector = selector.replace(/([.*+?^${}()|[\]\\])/g, "\\$1");
  const pattern = new RegExp(`${escapedSelector}\\s*\\{[^}]*\\}\\s*`, "g");
  return source.replace(pattern, "");
}
