import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { tsImport } from "tsx/esm/api";
import type { compileModule as compileModuleFn } from "../../../../packages/compiler/src/frontend/index";

type CompilerModule = {
  readonly compileModule: typeof compileModuleFn;
};

const compilerPath = fileURLToPath(new URL("../../../../packages/compiler/src/frontend/index.ts", import.meta.url));

async function main() {
  const sourcePath = fileURLToPath(new URL("../src/app.component.tsx", import.meta.url));
  const outputPath = fileURLToPath(new URL("../src/generated/app.generated.ts", import.meta.url));
  const compiler = await tsImport(pathToFileURL(compilerPath).href, import.meta.url) as CompilerModule;
  const source = await readFile(sourcePath, "utf8");
  const compiled = compiler.compileModule(source, {
    rootSymbol: "render"
  });

  if (!compiled.ok) {
    throw new Error(`${compiled.error.code}: ${compiled.error.message}`);
  }

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(
    outputPath,
    `/* @generated by examples/isolated/jue-current-app/scripts/compile.ts */\n${compiled.value.code}\n`,
    "utf8"
  );
}

void main();
