import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { tsImport } from "tsx/esm/api";
import type { compileModule as compileModuleFn } from "../packages/compiler/src/frontend/index";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const EXAMPLE_SRC = join(REPO_ROOT, "examples", "web-playground", "apps");
type CompilerModule = {
  readonly compileModule: typeof compileModuleFn;
};

async function main() {
  const compilerPath = fileURLToPath(new URL("../packages/compiler/src/frontend/index.ts", import.meta.url));
  const compilerUrl = pathToFileURL(compilerPath).href;
  const { compileModule } = await tsImport(compilerUrl, import.meta.url) as CompilerModule;
  const sourcePaths = await collectComponentSourcePaths(EXAMPLE_SRC);

  for (const sourcePath of sourcePaths) {
    const source = await readFile(sourcePath, "utf8");
    const compiled = compileModule(source);
    if (!compiled.ok) {
      throw new Error(`${sourcePath}: ${compiled.error.code}: ${compiled.error.message}`);
    }

    const outputPath = join(dirname(sourcePath), "generated", "page.generated.ts");
    await mkdir(dirname(outputPath), { recursive: true });

    await writeFile(
      outputPath,
      `/* @generated by scripts/compile-example-components.ts */\n${compiled.value.code}\n`,
      "utf8"
    );
  }
}

async function collectComponentSourcePaths(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const sourcePaths: string[] = [];

  for (const entry of entries) {
    const fullPath = join(directory, entry.name);

    if (entry.isDirectory()) {
      sourcePaths.push(...await collectComponentSourcePaths(fullPath));
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".component.tsx")) {
      sourcePaths.push(fullPath);
    }
  }

  return sourcePaths;
}

void main();
