import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { tsImport } from "tsx/esm/api";

const EXAMPLE_SRC = join(process.cwd(), "examples", "web-playground", "src");

async function main() {
  const compilerPath = fileURLToPath(new URL("../packages/compiler/src/frontend/index.ts", import.meta.url));
  const compilerUrl = pathToFileURL(compilerPath).href;
  const { compileModule } = await tsImport(compilerUrl, import.meta.url);
  const entries = await readdir(EXAMPLE_SRC, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".component.tsx")) {
      continue;
    }

    const sourcePath = join(EXAMPLE_SRC, entry.name);
    const source = await readFile(sourcePath, "utf8");
    const compiled = compileModule(source);
    if (!compiled.ok) {
      throw new Error(`${entry.name}: ${compiled.error.code}: ${compiled.error.message}`);
    }

    const outputPath = join(
      EXAMPLE_SRC,
      entry.name.replace(".component.tsx", ".generated.ts")
    );

    await writeFile(
      outputPath,
      `/* @generated by scripts/compile-example-components.ts */\n${compiled.value.code}\n`,
      "utf8"
    );
  }
}

void main();
